reddit-youtube/config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :posts do
    member do
      post 'upvote'
      post 'downvote'
      post 'create_comment'

    end
  end
  devise_for :users
  resources :subreddits do
    collection do 
      post :search 
    end

    member do 
      post 'join'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "my_subreddits", to: "subreddits#my_subreddits", as: "my_subreddits"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
   root "subreddits#index"
end

reddit-youtube/app/models/post.rb
class Post < ApplicationRecord

  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :subreddit
  belongs_to :user
  has_one_attached :image
  has_many :votes
  has_many :comments

  def total_score
    votes.sum(:value)
  end

end

reddit-youtube/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @vote = Vote.new
    @comment = Comment.new
    @comments = @post.comments
  end

  def create_comment
  
    @post = Post.friendly.find(params[:id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to @post, notice: "Comment successfully saved"
    else
      redirect_to @post, notice: "Failed to create comment"
    end

  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  # GET /posts/new
  def new
    @post = Post.new
    @subreddit = Subreddit.friendly.find(params[:subreddit_id])
  end


  def upvote
  @post = Post.find_by(slug: params[:id])
  @vote = current_user.votes.find_or_initialize_by(post: @post)
  @vote.value = 1
  @vote.save
  redirect_to @post

  end

  def downvote
  @post = Post.find_by(slug: params[:id])
  @vote = current_user.votes.find_or_initialize_by(post: @post)
  @vote.value = -1
  @vote.save
  redirect_to @post

  end


  # GET /posts/1/edit
  def edit
     @subreddit = @post.subreddit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.expect(post: [ :title, :body, :user_id, :subreddit_id, :image ])
    end
end

reddit-youtube/app/helpers/posts_helper.rb
module PostsHelper
end

reddit-youtube/app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.textarea :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.textarea :body %>
  </div>

  <%= form.file_field :image %>

  <div>
    <%= form.number_field :user_id, value: current_user.id, type:"hidden" %>
  </div>

  <div>
    <%= form.number_field :subreddit_id, value: @subreddit.id, type:"hidden" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

reddit-youtube/app/views/posts/_post.html.erb
<%= link_to post do %>
<div id="<%= dom_id post %>">
  <h2>
    <%= post.title %>
    <%=  [ post.total_score ] %>

  </h2>

  <p>
    <%= post.body %>
  </p>

  <% if post.image.present? %>
 <%= image_tag post.image, class:"post-image" %>
 <% end %>

</div>

<% end %>

<style>
.post-image {
  max-width: 100%;
  height: auto;
}



</style>

reddit-youtube/app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

reddit-youtube/app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Posts" %>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

reddit-youtube/app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

reddit-youtube/app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<% if current_user %>
<%= form_with(model: [@post, @vote], url: upvote_post_path, method: :post, id: "up-vote-form") do |form| %>
  <%= form.number_field :value, value: 1, type:"hidden" %>
  <%= form.submit "upvote" %>
<% end %>
<%= form_with(model: [@post, @vote], url: downvote_post_path, method: :post, id: "down-vote-form") do |form| %>
  <%= form.number_field :value, value: 1, type:"hidden"%>
  <%= form.submit "downvote" %>
<% end %>


<h3>Comments</h3>
<% @comments.each do |comment| %>
  <h5>
    <%= comment.content %> -
    <%= comment.user.email %>
  </h5>
<% end %>

<%= form_with(model: [@post, @comment], url: create_comment_post_path, method: :post) do |form| %>
  <h2> Add Comment </h2>
  <%= form.text_field :content%>
  <%= form.text_field :user_id, value: current_user.id, type:"hidden" %>
  <%= form.text_field :post_id, value: @post.id, type:"hidden"%>
  <%= form.submit %>
<% end %>
<% end %>


<% if current_user && current_user.id == @post.user_id %>
<div>
  <%= link_to 'Back to Subreddit', subreddit_path(@post.subreddit), class: 'btn btn-primary' %> |
  <%= link_to "Edit this post", edit_post_path(@post) %> 

  <%= button_to "Destroy this post", @post, method: :delete  %>
</div>
<% end %>