reddit-youtube/config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :posts do
    member do
      post 'upvote'
      post 'downvote'
      post 'create_comment'

    end
  end
  devise_for :users
  resources :subreddits do
    collection do 
      post :search 
    end

    member do 
      post 'join'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "my_subreddits", to: "subreddits#my_subreddits", as: "my_subreddits"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
   root "subreddits#index"
end

reddit-youtube/app/views/layouts/_navbar.html.erb
<div class="navbar">
  <div class="navbar-brand">

  </div>
  <div class="navbar-links">
    <%= link_to "Home", subreddits_path, class:"nav-link" %>
    <% if user_signed_in? %>
      <div class="navbar-user">
        <%= link_to "My Subreddits", my_subreddits_path, class: "nav-link" %>
        <%= link_to "Sign out", destroy_user_session_path, class: "nav-link", data: { turbo_method: :delete } %>
      <% else %>
        <div class="navbar-auth">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
        <% end %> 
        </div>
      </div>

reddit-youtube/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Reddit Youtube" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple-v1.css">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "layouts/navbar" %>
    <%= yield %>
  </body>
</html>