reddit-youtube/config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :posts do
    member do
      post 'upvote'
      post 'downvote'
      post 'create_comment'

    end
  end
  devise_for :users
  resources :subreddits do
    collection do 
      post :search 
    end

    member do 
      post 'join'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "my_subreddits", to: "subreddits#my_subreddits", as: "my_subreddits"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
   root "subreddits#index"
end

reddit-youtube/app/models/subreddit.rb
class Subreddit < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

      has_many :posts
      has_many :memberships
      belongs_to :user

end

reddit-youtube/app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController
  before_action :set_subreddit, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[new edit update create destroy ]

  # GET /subreddits or /subreddits.json
  def index
    @subreddits = Subreddit.all
  end

def search
  if params[:title_search].present?
    @subreddits = Subreddit.where("title LIKE ?", "%#{params[:title_search]}%")
  else
    @subreddits = []
  end

  respond_to do |format|
    format.turbo_stream do
      render turbo_stream: turbo_stream.update("search_results", partial: "subreddits/search_results", locals: { subreddits: @subreddits })
    end
  end
end


  # GET /subreddits/1 or /subreddits/1.json
  def show
    @membership = Membership.new
    @posts = @subreddit.posts
  end

  # GET /subreddits/new
  def new
    @subreddit = Subreddit.new
  end

  # GET /subreddits/1/edit
  def edit
  end

  def my_subreddits
    if current_user
      @user_memberships = current_user.memberships
    end
  end

  # POST /subreddits or /subreddits.json
  def create
    @subreddit = Subreddit.new(subreddit_params)

    respond_to do |format|
      if @subreddit.save
        format.html { redirect_to @subreddit, notice: "Subreddit was successfully created." }
        format.json { render :show, status: :created, location: @subreddit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subreddit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subreddits/1 or /subreddits/1.json
  def update
    if current_user && current_user.id == @subreddit.user_id # prevents user to create own button
      respond_to do |format|
        if @subreddit.update(subreddit_params)
          format.html { redirect_to @subreddit, notice: "Subreddit was successfully updated." }
          format.json { render :show, status: :ok, location: @subreddit }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @subreddit.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /subreddits/1 or /subreddits/1.json
  def destroy
    if current_user && current_user.id == @subreddit.user_id # prevents user to create own button
      @subreddit.destroy!

      respond_to do |format|
        format.html { redirect_to subreddits_path, status: :see_other, notice: "Subreddit was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_subreddit
    @subreddit = Subreddit.friendly.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def subreddit_params
    params.expect(subreddit: [ :title, :body, :user_id ])
  end
end

reddit-youtube/app/helpers/subreddits_helper.rb
module SubredditsHelper
end

reddit-youtube/app/views/subreddits/_form.html.erb
<%= form_with(model: subreddit) do |form| %>
  <% if subreddit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subreddit.errors.count, "error") %> prohibited this subreddit from being saved:</h2>

      <ul>
        <% subreddit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.textarea :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.textarea :body %>
  </div>

  <div>
    <%= form.number_field :user_id, value: current_user.id, type:"hidden" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

reddit-youtube/app/views/subreddits/_search_results.html.erb
<h2>Results:</h2>
<ul>

  <% @subreddits.each do |subreddit| %>
    <%= link_to subreddit, class: "search_result" do %>
      <li>
        <h3>
          R/<%= subreddit.title %>
        </h3>
      </li>
    <% end %>
  <% end %>

</ul>

reddit-youtube/app/views/subreddits/_subreddit.html.erb
<%= link_to subreddit do %>
<div id="<%= dom_id subreddit %>">
  <h1>
    R/<%= subreddit.title %>
  </h1>

  <h2>
   <%= subreddit.body %>
  </h2>

</div>
<% end %>

reddit-youtube/app/views/subreddits/edit.html.erb
<% content_for :title, "Editing subreddit" %>

<h1>Editing subreddit</h1>

<%= render "form", subreddit: @subreddit %>

<br>

<div>
  <%= link_to "Show this subreddit", @subreddit %> |
  <%= link_to "Back to subreddits", subreddits_path %>
</div>

reddit-youtube/app/views/subreddits/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Subreddits" %>

<h1>Subreddits</h1>
<%= link_to "New subreddit", new_subreddit_path %>
<h2>Search for Subreddits</h2>
<%= form_with url: search_subreddits_path, method: :post do |form| %>
  <%= form.search_field :title_search, oninput: "this.form.requestSubmit()", style:"width: 100%;" %>
<% end %>
<div id="search_results">
  Search Results
</div>


<div id="subreddits">
  <% @subreddits.each do |subreddit| %>
    <%= render subreddit %>
  <% end %>
</div>

reddit-youtube/app/views/subreddits/my_subreddits.html.erb
<% if @user_memberships.count > 0 %>
  <aside>
    <h2>My Subreddits</h2>
    <ul>
      <% @user_memberships.each do |membership| %>
        <% subreddit = membership.subreddit %>
        <% if subreddit.present? %>
          <li>
            <%= link_to subreddit.title, subreddit %>
          </li>
        <% end %>
      <% end %>

    </ul> 
  </aside?
<% end %>
  <%= link_to "New Subreddit", new_subreddit_path %>

reddit-youtube/app/views/subreddits/new.html.erb
<% content_for :title, "New subreddit" %>

<h1>New subreddit</h1>

<%= render "form", subreddit: @subreddit %>

<br>

<div>
  <%= link_to "Back to subreddits", subreddits_path %>
</div>

reddit-youtube/app/views/subreddits/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @subreddit %>

<% if current_user && current_user.memberships.exists?(subreddit_id: @subreddit.id) %>
  <p>VIP Member</p>
  <%= form_with(model: current_user.memberships.find_by(subreddit_id: @subreddit.id), method: :delete, local: true, style: "margin: 0;") do |form| %>
    <%= form.submit "Leave", class: "btn btn-danger" %>
<% end %>
  <% else %>
    <%= render partial: "memberships/form", locals: { membership: @membership } %>
  <% end %> 

<% if current_user && current_user.id == @subreddit.user_id %>
  <div >
    <%= link_to "Edit this subreddit", edit_subreddit_path(@subreddit) %> 
    <%= button_to "Destroy this subreddit", @subreddit, method: :delete %>
  </div>
<% end %>
<%= link_to "New Post", new_post_path(subreddit_id: @subreddit.id) %>
<%= link_to "Back to subreddits", subreddits_path %>

<%= render @posts %>